# This is a basic workflow to help you get started with Actions

name: GL.iNet snapshot firmware

# Controls when the action will run. 
on: 
  repository_dispatch:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: '0 17 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    timeout-minutes: 720

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # build source code
      - name: build
        run: |
          echo "COMPILE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
          cd ~/work/runner-script/sdk4_script && ./build_firmware_by_source $GITHUB_REPOSITORY $GITHUB_WORKSPACE $GITHUB_REF $GITHUB_RUN_ID $GITHUB_ACTOR snapshot

